version: "3.9"

services:
  db:
    image: postgres
    container_name: taskmanager_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
